### ISSUE TITLE
discovery-swarm heading toward deprecation

### ISSUE THREAD

**Issue by KyleMaas** [staltz/multiserver-dht#3]
It seems discovery-swarm is on the road to being deprecated in favor of hyperswarm.  See comments on this issue:

https://github.com/mafintosh/discovery-swarm/issues/65

**Comment by staltz** [comment]
Indeed.

**Comment by KyleMaas** [comment]
Should be fixed by #5

**Comment by KyleMaas** [comment]
#5 fixed this.
