### ISSUE TITLE
Separate peer creation from connecting

### ISSUE THREAD

**Issue by KyleMaas** [staltz/multiserver-dht#4]
I'm having trouble getting ssb-browser-demo to connect via DHT.  This seems to come down to the fact that to connect, multiserver-dht tries to create a peer first, and since createServer doesn't exist on the browser side, the connection crashes and fails.

So, would it be possible (especially with hyperswarm) to connect to another peer via DHT without creating a listening server?

**Comment by KyleMaas** [comment]
Assuming, of course, that the other peer is capable of listening and has a running listening port.

**Comment by staltz** [comment]
Have you seen https://gitlab.com/staltz/ssb-dht-invite ?

**Comment by KyleMaas** [comment]
Yes, and that's what ssb-browser-demo (and thereby ssb-browser-core) uses.  The problem comes in where accept() calls this.ssb.conn.connect() which is routed to multiserver-dht to do the connecting.  multiserver-dht's client connect operation calls createPeer() before trying to connect, which then creates a Swarm, which tries to call createServer() and crashes, crashing up the whole chain and preventing the connection from working.  It makes DHT-based connecting impossible in a browser.  What I'm requesting here is either one of the following:

1. createPeer() could create the Swarm (or Hyperswarm) object with listening turned off unless requested, with the server connecting turning that on, or
2. multiserver-dht's client connecting, which currently creates an independent (non-cached, non-global, non-member-variable) peer, could request that listening be turned off so that it acts purely as a client.

**Comment by KyleMaas** [comment]
#5 should fix this as well.

**Comment by KyleMaas** [comment]
#5 fixed this.
